CREATE TABLE anomaly_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detector_type   VARCHAR(50) NOT NULL,
    severity        VARCHAR(20) NOT NULL,
    event_type      VARCHAR(255),
    event_source    VARCHAR(255),
    event_id        VARCHAR(255),
    title           VARCHAR(500) NOT NULL,
    description     TEXT,
    details         JSONB,
    resolved        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE event_baselines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(255) NOT NULL,
    event_source    VARCHAR(255) NOT NULL,
    window_start    TIMESTAMPTZ NOT NULL,
    window_end      TIMESTAMPTZ NOT NULL,
    event_count     BIGINT NOT NULL,
    avg_count       DOUBLE PRECISION,
    stddev_count    DOUBLE PRECISION,
    UNIQUE (event_type, event_source, window_start)
);

CREATE TABLE schema_snapshots (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(255) NOT NULL,
    schema_hash     VARCHAR(64) NOT NULL,
    field_names     JSONB NOT NULL,
    sample_count    INTEGER NOT NULL,
    first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (event_type, schema_hash)
);

CREATE INDEX idx_alerts_detector ON anomaly_alerts(detector_type);
CREATE INDEX idx_alerts_event_type ON anomaly_alerts(event_type);
CREATE INDEX idx_alerts_created ON anomaly_alerts(created_at);
CREATE INDEX idx_alerts_resolved ON anomaly_alerts(resolved);
CREATE INDEX idx_baselines_type_source ON event_baselines(event_type, event_source);
CREATE INDEX idx_schemas_type ON schema_snapshots(event_type);
