CREATE TABLE pipeline_definitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL UNIQUE,
    description         VARCHAR(2000),
    source_topic        VARCHAR(255) NOT NULL,
    destination_topic   VARCHAR(255) NOT NULL,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    field_mappings      JSONB NOT NULL,
    error_handling      JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE dead_letter_events (
    id                  VARCHAR(255) PRIMARY KEY,
    pipeline_name       VARCHAR(255) NOT NULL,
    event_type          VARCHAR(255),
    event_source        VARCHAR(255),
    event_payload       JSONB,
    error_message       TEXT,
    retry_count         INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dead_letter_pipeline ON dead_letter_events(pipeline_name);
CREATE INDEX idx_dead_letter_created ON dead_letter_events(created_at);
